[app]
# how often will the transition zones be polled to see if we should swap focus
transition_poll_ms = 100

# multiple alt presses will force all clients to release their focus and
# unlock divice exclusive access
[escape_sequence]
key_count = 3
time_seconds = 1

# discovery service for finding peers
[discovery]
multicast_address = "239.2.3.239:2399"
# how many times will we look for servers before giving up and starting a new one
poll_count = 3
poll_interval_seconds = 2
# all peers sharing a cluster_id will be connected tho the same cluster
# using different cluster_id's will allow for harmony to run seperate clusters on the same
# network, this can also be done by using different multicast_address's
cluster_id = "default"

[server]
# web server
port = 4283

# websockets 
soc_writ_wait_second = 10
soc_close_grace_second = 10
